update: add update version in worklow

diff --git a/.github/workflows/ci-cd-docker.yml b/.github/workflows/ci-cd-docker.yml
--- a/.github/workflows/ci-cd-docker.yml
+++ b/.github/workflows/ci-cd-docker.yml
@@ -12,7 +12,7 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
 
-      - name: Fetch Current Version
+      - name: Fetch Current Version from MongoDB
         run: |
           response=$(curl --location --request POST 'https://ap-south-1.aws.data.mongodb-api.com/app/data-pkwvozw/endpoint/data/v1/action/findOne' --header 'Content-Type: application/json' --header 'Access-Control-Request-Headers: *' --header 'api-key: ${{ secrets.MONGO_DATA_API_TOKEN }}' --data-raw '{
             "collection":"releases",
@@ -22,13 +22,13 @@ jobs:
                 "project": "universe"
             }
           }')
-          echo $response
           version=$(echo $response | jq -r '.document | "\(.x).\(.y).\(.z)"')
           echo "version=$version" >> $GITHUB_ENV
 
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
+
+          - name: Login to Docker Hub
+          uses: docker/login-action@v3
+          with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
@@ -42,3 +42,24 @@ jobs:
           files: ./Dockerfile
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/private-repo-test:${{ env.version }}
+
+      - name: Update Current Version in MongoDB
+        run: |
+          response=$(curl --location --request POST 'https://ap-south-1.aws.data.mongodb-api.com/app/data-pkwvozw/endpoint/data/v1/action/updateOne' --header 'Content-Type: application/json' --header 'Access-Control-Request-Headers: *' --header 'api-key: ${{ secrets.MONGO_DATA_API_TOKEN }}' --data-raw '{
+            "collection":"releases",
+            "database":"deployment",
+            "dataSource":"Cluster0",
+            "filter": {
+              "project": "universe"
+            },
+            "update": {
+              "$inc": {
+                "z": 1
+              }
+            }
+          }')
+          echo "Update Response: $response"
+          if [[ "$response" != '{"matchedCount":1,"modifiedCount":1}' ]]; then
+            echo "Update to New Version failed"
+            exit 1
+          fi
